name: Deploy to Salesforce

on:
  push:
    branches:
      - main  # Runs when pushing to the 'main' branch
    paths:
      - 'force-app/**'  # Only trigger when files in 'force-app/' change

jobs:
  deploy_to_salesforce:
    runs-on: ubuntu-latest
    environment: Jackie-Kin
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last 2 commits for delta deployment

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate with Salesforce
        run: |
          echo ${{ secrets.JWT_SERVER_KEY }} | base64 --decode > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --alias deployment-org

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --source-dir force-app --target-org deployment-org --test-level RunLocalTests --wait 10
