name: Deploy to jinhaosfdc environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  deploy_to_jackie_kin:
    runs-on: ubuntu-latest
    environment: Jackie-Kin
    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      - name: 'Install sfdx git delta'
        run: | 
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: 'Create delta packages'
        run: | 
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta
          echo "[INFO] Diff generated"

      - name: 'Deploy to environment with running all local tests'
        run: |  
          echo ${{ secrets.JWT_SERVER_KEY }} | base64 --decode > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --alias MyAlias
