name: Deploy to Salesforce

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  deploy_to_salesforce:
    runs-on: ubuntu-latest  # Change to windows-latest if needed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Debug JWT Key
        run: |
          if [[ -z "${{ secrets.JWT_SERVER_KEY }}" ]]; then
            echo "Error: JWT_SERVER_KEY is empty or not set!"
            exit 1
          else
            echo "JWT_SERVER_KEY is set."
          fi

      - name: Decode JWT Key
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "${{ secrets.JWT_SERVER_KEY }}" | base64 -d > server.key
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo ${{ secrets.JWT_SERVER_KEY }} | certutil -decode -f - server.key
          fi

      - name: Authenticate with Salesforce
        run: |
          sf org login jwt --username ${{ secrets.SF_USERNAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --instance-url ${{ vars.SF_INSTANCE_URL }} \
            --set-default \
            --alias deployment-org

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --source-dir force-app --target-org deployment-org --test-level RunLocalTests --wait 10
